INSERT INTO regions (gu_name, dong_name) VALUES ('강남구', '강남동');
INSERT INTO regions (gu_name, dong_name) VALUES ('용산구', '용산동');
INSERT INTO regions (gu_name, dong_name) VALUES ('서대문구', '서대문동');
INSERT INTO regions (gu_name, dong_name) VALUES ('마포구', '마포동');
INSERT INTO regions (gu_name, dong_name) VALUES ('성동구', '성동동');
INSERT INTO regions (gu_name, dong_name) VALUES ('강북구', '강북동');
INSERT INTO regions (gu_name, dong_name) VALUES ('노원구', '노원동');
INSERT INTO regions (gu_name, dong_name) VALUES ('동작구', '동작동');
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 2879);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 3743);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 4088);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 3816);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 3247);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 1858);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 3753);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 2516);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 2609);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 3704);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 4090);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 2211);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 3301);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 2942);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 3102);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (2, 2258);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 2454);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 4039);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 2999);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 2505);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 3668);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 2015);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 2044);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 2601);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3629);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3709);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3887);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 2939);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3161);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 2243);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3052);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 2666);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3488);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 2457);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 1823);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2856);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2199);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 3634);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2315);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 1893);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2322);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 2213);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 3712);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 2406);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 3916);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 3179);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 4069);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 3965);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 4035);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 2848);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 2721);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 2918);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 2837);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3003);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 3405);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3167);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 2890);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3927);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 2014);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (7, 2180);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2290);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (3, 3734);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 2676);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (4, 3453);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 3710);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 1960);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3843);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (1, 2104);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (6, 1970);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 4181);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (8, 4156);
INSERT INTO apartment_rent (region_id, rent_price) VALUES (5, 3986);
INSERT INTO buildings (building_name, region_id) VALUES ('힐스테이트1', 1);
INSERT INTO buildings (building_name, region_id) VALUES ('리버뷰2', 1);
INSERT INTO buildings (building_name, region_id) VALUES ('힐스테이트3', 2);
INSERT INTO buildings (building_name, region_id) VALUES ('리버뷰4', 3);
INSERT INTO buildings (building_name, region_id) VALUES ('드림타워5', 4);
INSERT INTO buildings (building_name, region_id) VALUES ('현대하우스6', 5);
INSERT INTO buildings (building_name, region_id) VALUES ('럭셔리하이츠7', 6);
INSERT INTO buildings (building_name, region_id) VALUES ('럭셔리하이츠8', 6);
INSERT INTO buildings (building_name, region_id) VALUES ('리버뷰9', 7);
INSERT INTO buildings (building_name, region_id) VALUES ('현대하우스10', 8);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (1, 4038, 110, 14, 268);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (1, 3507, 59, 7, 468);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (1, 628, 117, 14, 283);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (2, 1065, 48, 14, 399);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (2, 3938, 74, 1, 481);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (2, 4285, 120, 5, 158);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (3, 1490, 55, 13, 368);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (3, 2514, 73, 9, 135);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (3, 2070, 54, 15, 437);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (4, 4314, 52, 15, 465);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (4, 508, 54, 14, 464);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (4, 2226, 63, 11, 378);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 3742, 65, 15, 392);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 4824, 57, 13, 360);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (6, 590, 118, 1, 122);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (6, 1627, 70, 10, 123);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (6, 1591, 54, 10, 293);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (7, 596, 57, 2, 438);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (7, 4890, 51, 9, 334);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (8, 2407, 53, 11, 473);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (8, 843, 43, 3, 470);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (8, 1658, 95, 9, 350);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (9, 1781, 66, 4, 371);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (9, 1516, 70, 13, 331);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 3626, 50, 8, 317);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 4497, 73, 5, 286);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (7, 3479, 86, 3, 229);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (3, 3284, 108, 13, 509);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 3847, 76, 13, 611);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (2, 4846, 72, 3, 178);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (4, 1161, 47, 10, 912);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 4452, 73, 6, 516);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (1, 2737, 105, 6, 806);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (6, 1095, 110, 5, 982);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 1796, 92, 5, 339);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (2, 4885, 57, 14, 914);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 3969, 106, 9, 384);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (9, 850, 108, 11, 744);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 1993, 56, 2, 882);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (8, 2209, 112, 2, 446);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 1775, 96, 9, 140);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (7, 3217, 97, 3, 926);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 4054, 76, 13, 802);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (10, 1158, 102, 6, 101);
INSERT INTO rooms (building_id, deposit, monthly_rent, floor, room_num) VALUES (5, 3969, 46, 8, 940);
INSERT INTO users (login_id, password, email, user_name) VALUES ('user1', 'pass1234', 'user1@example.com', '이영수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user2', 'pass1234', 'user2@example.com', '임정남');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user3', 'pass1234', 'user3@example.com', '한성수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user4', 'pass1234', 'user4@example.com', '송윤서');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user5', 'pass1234', 'user5@example.com', '강채원');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user6', 'pass1234', 'user6@example.com', '권상훈');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user7', 'pass1234', 'user7@example.com', '최영길');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user8', 'pass1234', 'user8@example.com', '안윤서');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user9', 'pass1234', 'user9@example.com', '이영진');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user10', 'pass1234', 'user10@example.com', '김경자');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user11', 'pass1234', 'user11@example.com', '김철수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user12', 'pass1234', 'user12@example.com', '이영희');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user13', 'pass1234', 'user13@example.com', '박민수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user14', 'pass1234', 'user14@example.com', '최은지');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user15', 'pass1234', 'user15@example.com', '정현우');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user16', 'pass1234', 'user16@example.com', '한서연');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user17', 'pass1234', 'user17@example.com', '장도윤');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user18', 'pass1234', 'user18@example.com', '윤지후');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user19', 'pass1234', 'user19@example.com', '김가은');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user20', 'pass1234', 'user20@example.com', '이준호');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user21', 'pass1234', 'user21@example.com', '이영수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user22', 'pass1234', 'user22@example.com', '김현정');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user23', 'pass1234', 'user23@example.com', '박현주');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user24', 'pass1234', 'user24@example.com', '이영자');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user25', 'pass1234', 'user25@example.com', '성현준');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user26', 'pass1234', 'user26@example.com', '이성수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user27', 'pass1234', 'user27@example.com', '강하은');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user28', 'pass1234', 'user28@example.com', '서성호');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user29', 'pass1234', 'user29@example.com', '장주원');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user30', 'pass1234', 'user30@example.com', '정성수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user31', 'pass1234', 'user31@example.com', '이예린');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user32', 'pass1234', 'user32@example.com', '정지현');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user33', 'pass1234', 'user33@example.com', '김성우');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user34', 'pass1234', 'user34@example.com', '박서현');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user35', 'pass1234', 'user35@example.com', '이주호');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user36', 'pass1234', 'user36@example.com', '장하늘');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user37', 'pass1234', 'user37@example.com', '윤하림');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user38', 'pass1234', 'user38@example.com', '최윤석');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user39', 'pass1234', 'user39@example.com', '한지수');
INSERT INTO users (login_id, password, email, user_name) VALUES ('user40', 'pass1234', 'user40@example.com', '김은재');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (1, 8, 1497, 4103, 60, 105, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (2, 7, 1389, 2582, 36, 77, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (3, 7, 1725, 3592, 56, 90, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (4, 1, 2379, 4717, 71, 94, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (5, 1, 1824, 4315, 51, 96, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (6, 2, 1509, 2901, 42, 79, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (7, 8, 1287, 3151, 41, 69, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (8, 8, 1511, 4301, 34, 68, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (9, 2, 1103, 3438, 64, 110, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (10, 1, 2984, 4175, 78, 125, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (11, 1, 1500, 4500, 50, 130, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (12, 2, 2000, 5000, 60, 140, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (13, 3, 1000, 3000, 40, 120, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (14, 4, 1200, 3500, 45, 110, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (15, 5, 1300, 4000, 55, 135, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (16, 6, 900, 2600, 35, 95, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (17, 7, 1100, 3200, 50, 115, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (18, 8, 1400, 4700, 65, 145, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (19, 1, 2000, 6000, 70, 150, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (20, 2, 1000, 3000, 45, 100, '2025-05-23');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (21, 5, 2662, 4067, 80, 114, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (22, 8, 2302, 4765, 63, 110, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (23, 3, 1968, 3256, 43, 89, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (24, 5, 1797, 2815, 31, 63, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (25, 2, 2578, 4887, 80, 123, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (26, 4, 1292, 4235, 78, 122, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (27, 4, 2697, 4666, 41, 74, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (28, 5, 1607, 3681, 54, 86, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (29, 7, 2178, 4634, 79, 120, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (30, 8, 1237, 3380, 66, 110, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (31, 3, 1065, 3109, 77, 98, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (32, 1, 2041, 3917, 54, 86, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (33, 4, 1041, 2273, 34, 61, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (34, 7, 1547, 3181, 63, 106, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (35, 3, 2832, 5092, 60, 109, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (36, 6, 2364, 5325, 52, 83, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (37, 7, 1570, 2721, 57, 84, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (38, 7, 1000, 2595, 64, 85, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (39, 6, 2553, 5266, 75, 116, '2025-05-22');
INSERT INTO user_preference (user_id, region_id, deposit_min, deposit_max, rent_min, rent_max, created_at) VALUES (40, 8, 1843, 3364, 58, 82, '2025-05-22');